### ISSUE TITLE
Refresh token TTL less than an hour.

### ISSUE THREAD

**Issue by mikey0000** [electrickiwi-nz/api-samples#18]
Hi Matt,

As of recent the token isn't lasting very long/expiring for HA users (myself included) and the API seems to be returning 500 when the token is expired. Can you please let me know if you can shed some light on the below errors, if they are coming from your server or nabucasa's?

Error fetching Electric Kiwi HOP Data data: Error communicating with EK API: Error request failed: 412
Authentication failed while fetching Electric Kiwi HOP Data data: Access token failure: 500, message='Internal Server Error', url=URL('https://account-link.nabucasa.com/refresh_token/electric_kiwi')

Getting hold of Nabucasa isn't always very easy.

Can you confirm the refresh token lasts longer than the access token? Did you change the refresh token time to 5 days for Home Assistant?

**Comment by mikey0000** [comment]
So I investigated further and the ttl for the refresh token is less than 1 hour.

ttl: 2400
expires_in: 1200

Can you please increase the ttl of the refresh token to 5 days thanks.

This is affecting all users of Home Assistant that use my integration to the EK API

**Comment by mikey0000** [comment]
It would be really great if you could get in contact with NabuCasa and figure out why the refresh endpoint is returning 500 but I think its due to the refresh token expiring, if its them or you :man_shrugging:

**Comment by mikey0000** [comment]
On further investigation it looks like the refresh token is being forcefully expired everyday. Which means users are having to re-configure the EK integration every day. This has also been my experience lately. There is definitely a bug somewhere with the recent release.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - I am sorry for the inconvenience caused - I have been working with the team to understand what has changed and the details you posted have helped track down the issue. 

We have implemented TTLs on the bearer tokens that have caused the refresh_token to stop working. There is a fix going on this evening that should solve this issue and at the same time, the refresh_token expiry will be adjusted to 5 days. 

I will update you once this fix is in place. Cheers, Matt

**Comment by mikey0000** [comment]
Awesome! Thanks so much for the update Matt.

**Comment by mikey0000** [comment]
So I have one user who this is resolved for and one user who is getting 500's every time the token tries to refresh. If you could take a look that would be great, I can also get them to reach out as I think its isolated to them/some users. My account is fine and doesn't seem to have any issues.

**Comment by mikey0000** [comment]
Small update, user who raised issue on HA github is still having the same problem, oddly I am not.

**Comment by PaulCavill** [comment]
@electrickiwi-nz

Below is the times and messages of the last issue.

Maybe you can check your server side logs?


```
2023-09-08 20:46:56.433 DEBUG (MainThread) [homeassistant.components.electric_kiwi.coordinator] Finished fetching Electric Kiwi HOP Data data in 0.154 seconds (success: True)

2023-09-08 20:46:56.433 DEBUG (MainThread) [homeassistant.components.electric_kiwi.select] Setting up select entity

2023-09-08 22:46:58.201 ERROR (MainThread) [homeassistant.components.electric_kiwi.coordinator] Authentication failed while fetching Electric Kiwi HOP Data data: Access token failure: 500, message='Internal Server Error', url=URL('https://account-link.nabucasa.com/refresh_token/electric_kiwi')

2023-09-08 22:46:58.205 DEBUG (MainThread) [homeassistant.components.electric_kiwi.coordinator] Finished fetching Electric Kiwi HOP Data data in 2.090 seconds (success: False)
```

--//Manually reconfigure integration 

```
2023-09-08 23:12:38.948 INFO (MainThread) [homeassistant.components.electric_kiwi.config_flow] Successfully authenticated

2023-09-08 23:12:39.536 DEBUG (MainThread) [homeassistant.components.electric_kiwi.coordinator] Finished fetching Electric Kiwi HOP Data data in 0.293 seconds (success: True)

2023-09-08 23:12:39.537 DEBUG (MainThread) [homeassistant.components.electric_kiwi.select] Setting up select entity

2023-09-09 01:12:41.432 ERROR (MainThread) [homeassistant.components.electric_kiwi.coordinator] Authentication failed while fetching Electric Kiwi HOP Data data: Access token failure: 500, message='Internal Server Error', url=URL('https://account-link.nabucasa.com/refresh_token/electric_kiwi')

2023-09-09 01:12:41.434 DEBUG (MainThread) [homeassistant.components.electric_kiwi.coordinator] Finished fetching Electric Kiwi HOP Data data in 2.160 seconds (success: False)

```
--//Manually reconfigure integration 

```
2023-09-09 08:08:47.224 INFO (MainThread) [homeassistant.components.electric_kiwi.config_flow] Successfully authenticated

2023-09-09 08:08:47.648 DEBUG (MainThread) [homeassistant.components.electric_kiwi.coordinator] Finished fetching Electric Kiwi HOP Data data in 0.170 seconds (success: True)

2023-09-09 08:08:47.649 DEBUG (MainThread) [homeassistant.components.electric_kiwi.select] Setting up select entity
```

**Comment by PaulCavill** [comment]
Also get the below some times

https://welcome.electrickiwi.co.nz/oauth/authorize?client_id=*redacted*&response_type=code&state=*redacted*&redirect_uri=https://account-link.nabucasa.com/authorize_callback&scope=read_connection_detail+read_billing_frequency+read_account_running_balance+read_consumption_summary+read_consumption_averages+read_hop_intervals_config+read_hop_connection+save_hop_connection+read_session

Bad Request
The CSRF session token is missing.

**Comment by PaulCavill** [comment]
@electrickiwi-nz @matthuisman any changes on the EK API yet, to resolve this issue?

**Comment by matthuisman** [comment]
electrickiwi matt != me

**Comment by electrickiwi-nz** [comment]
@PaulCavill - sorry that you are having trouble with the login - we are able to reproduce the issue but can't find anything specific within the logs and therefore its taking us a little bit to figure out what is going on. 

We have been having trouble with our refresh tokens and how they are working and have put in some changes that should be helping, expiry times and additional logging. 

The team area looking into this issue and I am hoping for some resolutions over the next couple of days.

**Comment by electrickiwi-nz** [comment]
@mikey0000 

Sorry that you have user issues coming through - we are working through it at the moment. In the meantime the refresh_token should now have a 5 day expiry specific to your HA application. 

Cheers, Matt

**Comment by PaulCavill** [comment]
@electrickiwi-nz Not sure if this is related but I get an error every time I try login via a computer.

![image](https://github.com/electrickiwi-nz/api-samples/assets/108971756/bd02fbde-5bc7-403f-8c2c-158f96307ac3)

**Comment by mikey0000** [comment]
Yeah welcome.electrickiwi... Is broken right now.

**Comment by electrickiwi-nz** [comment]
@mikey0000 and @PaulCavill - the team have been strengthening our security practices and added CSPs specific to `form-action` without fully testing our Juice Hacker integrations. This has caused some issues which are now fixed and working. 

Sorry for the hassle ... let me know if there are any other issues you come across.
